; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c3
framework = arduino
board_build.partitions = huge_app.csv
lib_deps = 
	moononournation/GFX Library for Arduino@^1.6.7
	https://github.com/MaliosDark/Arduino_GC9B72.git
	adafruit/Adafruit GFX Library@^1.12.6
	bblanchon/ArduinoJson@^7.2.2
